CREATE TABLE IF NOT EXISTS "categories" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS "difficulties" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "level" INTEGER UNIQUE NOT NULL,
    "name" TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS "history" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "category_id" INTEGER NOT NULL,
    "difficulty_id" INTEGER NOT NULL,
    "sub_category" TEXT NOT NULL,
    "words" TEXT NOT NULL,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP
);